spring:
  application:
    name: springboot3-restful-project
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/restful_with_springboot?useTimezone=true&serverTimezone=UTC
    username: root
    password: amoraiany123

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
    show-sql: false
    open-in-view: false

logging:
  level:
  # br.com.deceitful1: warn
    root: warn


